### PR TITLE
Add wpcalypso/redux-no-bound-selectors rule as error

### PR DESCRIPTION
**Pull request by mcsf**
See https://github.com/Automattic/eslint-plugin-wpcalypso/pull/38/ and https://github.com/Automattic/wp-calypso/issues/14024

### CODE REVIEW

**Comment by deBhal** [comment]
Given the 👍  from @aduth, I'm going to go ahead and merge this so I can base my PR on it.

I'm going to hold off on pushing the tag for now, though, so we can potentially bundle this, #9 and #5 in the one release.

**Comment by mcsf** [comment]
Woot! Could anyone publish this to NPM or, alternatively, add me (`mcsf`) to the module?

**Comment by aduth** [comment]
>Woot! Could anyone publish this to NPM or, alternatively, add me (`mcsf`) to the module?

I added you, but per @deBhal's comment, let's wait and include a few more changes in the same release.

**Comment by aduth** [comment]
We probably should have bumped the peer dependency for `eslint-plugin-wpcalypso` in this one, since obviously the rule won't exist until `3.4.0`.

**Pull request merged**
